---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: aks-helloworld
  name: aks-helloworld
spec:
  containers:
  - image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
    name: aks-helloworld
    ports:
    - containerPort: 80
    env:
     - name: TITLE
       value: "Welcome to Azure Kubernetes Service (AKS)"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

